import MainLayout from "@/components/shared/MainLayout";
import { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function MainGroupLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="body">
            <MainLayout>
                {children}
            </MainLayout>
        </div>
    );
}