import MainLayout from "@/components/shared/MainLayout";
import { getCategories, getNationals } from "@/services/movie";
import { CategoryReponse, NationalReponse } from "@/types/movie";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function MainGroupLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [categoryReponse, nationalReponse] = await Promise.all([
    getCategories<CategoryReponse>(),
    getNationals<NationalReponse>(),
  ]);

  const categories = categoryReponse.items;
  const nationals = nationalReponse.items;

  return (
    <div className="body">
      <MainLayout categoriesMovie={categories} nationsMovie={nationals}>
        {children}
      </MainLayout>
    </div>
  );
}
